### ISSUE TITLE
Problem install on M1 mac.

### ISSUE THREAD

**Issue by AnthonyLaw** [symbol/wallets-lib#6]
![image](https://user-images.githubusercontent.com/5649156/148796031-6eeb2e75-fcb0-432d-bfa5-a0b572526afa.png)

**Comment by Jaguar0625** [comment]
what is `node --version` ?

**Comment by cryptoBeliever** [comment]
@AnthonyLaw 
https://github.com/Automattic/node-canvas/issues/1511

```
If you have an ARM CPU
Prebuilds aren't available for ARM. Please see the wiki for guides on building from source. See also node-gfx/node-canvas-prebuilt#69.
```
So I think works as designed. You have to build from sources.

**Comment by AnthonyLaw** [comment]
> what is `node --version` ?

v16.7.0

**Comment by Jaguar0625** [comment]
https://github.com/Automattic/node-canvas

try running this first:
```sh
brew install pkg-config cairo pango libpng jpeg giflib librsvg
```

**Comment by AnthonyLaw** [comment]
Alright, thanks.
It's working!!
